export const USER_TYPES = {
  STANDARD: 'STANDARD_USER',
  LOCKED: 'LOCKED_USER',
  PROBLEM: 'PROBLEM_USER',
  PERFORMANCE: 'PERFORMANCE_USER',
  ERROR: 'ERROR_USER',
  VISUAL: 'VISUAL_USER',
} as const;